#!/usr/bin/python
try:
	from feedparser import feedparser
	from getopt import getopt
	import requests
	import time
	import traceback
	import sys
except ImportError as e:
	print e
	print 'Ensure that /usr/bin/python is a python 2.7 shell.'
	exit(99)

class rsnews:

	__RSS_URL = 'http://services.runescape.com/m=news/latest_news.rss'

	def __init__(self):
		dump = feedparser.parse(self.__RSS_URL)
		self.__logs = dump['entries']

	def to_string(self, l = 10):
		if self.__logs == []:
			return "Could not access RuneScape. Ensure there is an internet connection, and that RuneScape.com is up."
		out = ""
		i = 0
		for log in self.__logs:
			if i == l: break

			out += log['title'] + "\n"
			out += "\t" + log['summary'] + "\n"
			out += "\t" + log['published'] + "\n"
			out += log['link'] + "\n\n"

			print
			i += 1
		return out 

if __name__ == "__main__":
	err_msg = 'rsnews [ -h ] [ -n num_posts ]'
	help_msg = 'NAME:\n' + \
		'\trsnews - displays the most recent news from RuneScape.\n\n' + \
		'USAGE:\n' + \
		'\trsnews [OPTIONS]\n\n' + \
		'OPTIONS:\n' + \
		'\t-h\n' + \
		'\t\tDisplay this help text.\n\n' + \
		'\t-n num_posts\n' + \
		'\t\tDisplay `num_posts` news posts.\n'

	try:
		opts, args = getopt(sys.argv[1:], "hn:lst")
	except:
		print err_msg
		exit(1)

	limit = 10

	for flag, value in opts:
		if flag == '-n':
			if value is None: continue
			try:
				limit = int(value)
			except:
				print '-n requires an integer value'
				print err_msg
				exit(4)
		elif flag == '-h':
			print help_msg
			exit(0)

	rsn = rsnews()

	print rsn.to_string(l = limit)