#!/usr/bin/python
try:
	from getopt import getopt
	import requests
	import sys
except ImportError as e:
	print e
	print 'Ensure that /usr/bin/python is a python 2.7 shell.'
	exit(99)

if __name__ == "__main__":
	err_msg = 'rstrack [ -h ] [ -v ] user0 [ user1 [ user2 ... ]]'
	help_msg = 'NAME:\n' + \
		'\trstrack - updates RuneTracker for particular users.\n\n' + \
		'USAGE:\n' + \
		'\trstrack [OPTIONS] user0 [ user1 [ user2 ... ]]\n\n' + \
		'\tUpdates users user0, user1, user2, etc.\n\n' + \
		'OPTIONS:\n' + \
		'\t-h\n' + \
		'\t\tDisplay this help text.\n\n' + \
		'\t-v\n' + \
		'\t\tRead the responses to standard out.\n'

	try:
		opts, args = getopt(sys.argv[1:], "vh")
	except:
		print err_msg
		exit(1)

	verbose = False

	for flag, value in opts:
		if flag == '-h': 
			print help_msg
			exit(0)
		elif flag == '-v': verbose = True

	if not args:
		print err_msg
		exit(2)

	for arg in args:
		r = requests.get("http://runetracker.org/updateUserJS.php?user=" + arg)
		if verbose: print r.text